server:
  port: 50004

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"



turbine:
  app-config: spring-cloud-zk-producer, spring-cloud-zk-consumer-feign-spring-cloud ##需要监控的服务名
  aggregator:
    clusterConfig: default    ##需要监控的服务集群名
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream    ##key是clusterConfig集群的名字，value是hystrix监控的后缀，springboot2.0为actuator/hystrix.stream