spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/




server:
  port: 18000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream